
# Get all Persons
GET http://localhost:3001/api/persons


###

# Get Single Person by Id
GET http://localhost:3001/api/persons/3


###

# Get Single Person by Id (test for  invalid user id)
GET http://localhost:3001/api/persons/999

###

# Create new phonebook entry
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Abolade Benjamin",
    "number": "090-2266-8728"
}

###

# Delete Person By id
DELETE  http://localhost:3001/api/persons/3